branches:
  only: 
    - master
    - v2-master
language: php
dist: trusty
sudo: false
php:
    - 7.4
before_install: "composer install --ignore-platform-reqs"
script: "cd test && phpunit UnitTests.php"
