branches:
  only: 
    - master
language: php
dist: trusty
sudo: false
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
before_install: "composer install --ignore-platform-reqs"
script: "cd test && phpunit UnitTests.php && phpunit OAuthTests.php"
